### ISSUE TITLE
Meson support

### ISSUE THREAD

**Issue by zt64** [pschichtel/dockcross-gradle-plugin#2]
How would I go about using meson with this? I'm trying to get it to work but it just fails saying `ERROR: Could not execute Java compiler: javac`

**Comment by pschichtel** [comment]
Hi, you should be able to run meson just fine in the dockcross containers, this plugin barely assists in running stuff in these containers. Can you elaborate on what you are trying to do?

**Comment by zt64** [comment]
I'm trying to use meson instead of cmake but for some reason it's unable to find JNI headers. The JAVA_HOME env var is set to /java-toolchain, and it does exist, so I'm not really sure what's going on. The error: `ERROR: Could not execute Java compiler: javac` indicates its falling back to javac as it couldn't find the headers

**Comment by pschichtel** [comment]
Would it be possible for you to share your project (or possibly a simplified version of it) ? I have little experience with meson, so being able to run this for myself would be great.

**Comment by zt64** [comment]
Currently it's a bit of a mess, experimenting with different build systems and stuff: https://github.com/zt64/mpv-kt

**Comment by zt64** [comment]
I've fixed it by just including the jni headers as a part of my project instead of trying to lookup through the system with meson

**Comment by pschichtel** [comment]
Ah so just meson's discovery wasn't working? I've had trouble with cmake's discovery too, because it sometimes attempts to invoke some programs, which are either not there or are from a different architecture. Also if you are cross compiling for unixoids and windows, you might need to vendor the JNI headers, because unix java only bundles unix headers and windows java only bundles windows headers.

see: https://github.com/pschichtel/libdatachannel-java/tree/main/jni/jdk
